

version: '3.7'

services:
  projects_database:
    image: postgres
    container_name: projects_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ceapp-api
    volumes:
      - pgdata:/data/postgres
  app: 
    build: .
    container_name: ceapp-api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - projects_database
    depends_on:
      - projects_database
volumes:
  pgdata:
    driver: local